# Permalinks
permalink:           pretty

# Setup
title:               Tiago Donato
# tagline:             The Jekyll Butler
url:                 https://tgdnt.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Tiago Donato
  url:               https://tgdnt.com
  email:             tgdnt@pm.me

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
