## Permalinks
permalink: pretty

## Setup
title: Tiago Donato
url: https://tgdnt.com
baseurl: ""
repo_name: tgdnt/tgdnt.com
timezone: America/Chicago

nav:
  - title: About
    url: /about
  - title: Blog
    url: /blog
paginate: 1
paginate_path: "/blog/page:num/"
exclude: ["/_orgsource"]
# related_posts: yes

defaults:
  -
    scope:
      path: ""
    values:
      author: "Tiago Donato"
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Tiago Donato"

## Social links:
# facebook: myfacebook
twitter: tgdnt
# google: mygoogle
instagram: tgdnt
# pinterest: mypinterest
linkedin: tiagodonato
# youtube: tiagodonato@gmail.com
# spotify: myspotify
github: tgdnt
# gitlab: mygitlab
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: tiagodonato
# lanyrd: mylanyrd
mastodon: masto.donte.com.br/@tgdnt
email: tgdnt@pm.me

avatar:
  alt: "Tiago Donato"
  url: assets/images/avatar.jpg
## Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: :compressed

## About/contact
author:
  name: Tiago Donato
  url: https://tgdnt.com
  email: tgdnt@pm.me

## Gems
plugins:
  - jekyll-paginate
  - jekyll-feed
#  - classifier-reborn
#  - jekyll-seo-tag
#  - jekyll-archives
