## Permalinks
permalink: pretty

## Setup
title: Tiago Donato
url: https://tgdnt.com
baseurl: ""
repo_name: tgdnt/tgdnt.com
nav:
  - title: Home
    url: /
  - title: Blog
    url: /blog
paginate: 1
paginate_path: "/blog/page:num/"
excerpt_separator: <!--more-->
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Tiago Donato"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
## Social links:
github: tgdnt
email: tgdnt@pm.me

avatar:
  alt: "Tiago Donato"
  url: assets/images/avatar.jpg
## Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: :compressed

## About/contact
author:
  name: Tiago Donato
  url: https://tgdnt.com
  email: tgdnt@pm.me

## Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
#  - jekyll-org
