## Permalinks
permalink: :slug

## Setup
title: Tiago Donato
url: https://tgdnt.com
baseurl: ""
timezone: America/Chicago

nav:
  - title: About
    url: /about
  - title: Blog
    url: /blog
paginate: 3
paginate_path: "/blog/page:num/"
exclude: ["/_orgsource"]
no_related_posts: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Tiago Donato"
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Tiago Donato"
      license: "CC-BY-SA"

## Social links:
# facebook: myfacebook
twitter: tgdnt
# google: mygoogle
instagram: tgdnt
# pinterest: mypinterest
linkedin: tiagodonato
# youtube: tiagodonato@gmail.com
# spotify: myspotify
github: tgdnt
# gitlab: mygitlab
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: tiagodonato
# lanyrd: mylanyrd
mastodon: masto.donte.com.br/@tgdnt
keybase: tgdnt
email: tiago@tgdnt.com

comment_to_email: tiago@tgdnt.com

avatar:
  alt: "Tiago Donato"
  url: assets/images/avatar.jpg
## Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: :compressed

## About/contact
author:
  name: Tiago Donato
  url: https://tgdnt.com
  email: tiago@tgdnt.com

## Gems
plugins:
  - jekyll-paginate
  - jekyll-feed
#  - classifier-reborn
#  - jekyll-seo-tag
#  - jekyll-archives
