## Permalinks
permalink: /:slug/

## Setup
title: Tiago Donato
# description: 
lang: en_US
author: Tiago Donato
logo: /assets/images/site-logo.png
url: https://www.tgdnt.com
baseurl: ""
timezone: America/Chicago

nav:
  - title: About
    url: /about
  - title: Projects
    url: /projects
  - title: Blog
    url: /blog
paginate: 2
paginate_path: "/blog/page:num/"
exclude: [_orgsource, vendor, Gemfile, Gemfile.lock]
no_related_posts: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      license: "by-sa"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      license: "by-sa"

## Social links:
## Use variables:
##   slug: matching the fork-awesome slug
##   title: what you want to see in the overlay
##   url: what you want the icon to link to
social-icons:
  -
    slug: linkedin
    title: linkedin.com/in/tiagodonato
    url: https://linkedin.com/in/tiagodonato
  -
    slug: github
    title: github.com/tgdnt
    url: https://github.com/tgdnt
  -
    slug: mastodon
    title: masto.donte.com.br/@tgdnt
    url: https://masto.donte.com.br/@tgdnt
  -
    slug: keybase
    title: keybase.io/tgdnt
    url: https://keybase.io/tgdnt
  -
    slug: envelope
    title: tiago@tgdnt.com
    url: mailto:tiago@tgdnt.com

comments_email: tiago@tgdnt.com

avatar:
  alt: "Tiago Donato"
  url: assets/images/avatar.jpg
## Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: :compressed

## Gems
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
#  - classifier-reborn
#  - jekyll-archives

# Additional data for jekyll-seo-tag
social:
  name: Tiago Donato
  links:
    - https://masto.donte.com.br/@tgdnt
    - https://linkedin.com/in/tiagodonato
    - https://keybase.io/tgdnt
    - https://github.com/tgdnt
